Lab 6
Dziodzi/webs_5_semester pull request #6
Opened 2022-12-19 03:27 UTC by Dziodzi

2022-12-19 11:41 UTC, BakasaRus requested changes
1. На странице с отзывами сделай так, чтобы в случае переноса какой-то карточки пустое место под неё пропорционально разделялось под оставшиеся карточки в этой строке

2022-12-19 11:41 UTC, BakasaRus commented on styles/table.css
> +    grid-template-columns: 34% 22% 22% 22%;
Если я добавлю `grid-gap`, то табличка поедет

2022-12-19 11:41 UTC, BakasaRus commented on index.html
> +            <li><a class="navbar-button active" href="index.html">Главная</a></li>
Подсвечивать пункт меню нужно через JS, не указывая класс в HTML

2022-12-19 11:41 UTC, BakasaRus commented on js/showLoadingTime.js
> +window.addEventListener('load', event => showLoadingTime());
Чем это отличается от `window.onload`?

2022-12-19 12:36 UTC, Dziodzi commented on js/showLoadingTime.js
> +window.addEventListener('load', event => showLoadingTime());
window.onload
По умолчанию он запускается при загрузке всей страницы, включая ее содержимое (изображения, CSS, скрипты и т.д.). Событие load на объекте window наступает, когда загрузилась вся страница, включая стили, картинки и другие ресурсы. 

document.onload (загрузка документа)
Он вызывается, когда DOM готов, что может быть до загрузки изображений и другого внешнего контента.

2022-12-19 12:37 UTC, Dziodzi commented on index.html
> +            <li><a class="navbar-button active" href="index.html">Главная</a></li>
Done

2022-12-19 12:41 UTC, Dziodzi commented on styles/table.css
> +    grid-template-columns: 34% 22% 22% 22%;
Done

2022-12-19 13:37 UTC, BakasaRus requested changes

2022-12-19 13:37 UTC, BakasaRus commented on js/planner.js
> +    const idea = formData.get('idea');
Вот тут было бы неплохо обрабатывать пробелы в начале и в конце строки

2022-12-19 13:37 UTC, BakasaRus commented on js/planner.js
> +        alert('Напиши бизнес-план, бизнес-брат!');
А это можно проверять ещё и на стороне браузера

2022-12-19 13:50 UTC, Dziodzi commented on js/planner.js
> +        alert('Напиши бизнес-план, бизнес-брат!');
Done

2022-12-19 13:50 UTC, Dziodzi commented on js/planner.js
> +    const idea = formData.get('idea');
Done

2022-12-19 14:11 UTC, BakasaRus commented on styles/table.css
> +    grid-template-columns: 34% 22% 22% 22%;
Тут лучше использовать единицу измерения `fr`

2022-12-19 14:19 UTC, BakasaRus requested changes
Попробуй выводить в карточку отзыва почту автора

2022-12-20 00:14 UTC, Dziodzi commented
> 

Done

2022-12-26 10:59 UTC, BakasaRus approved these changes

2022-12-26 11:17 UTC, merged